import { Effects } from "./Utilities";

export enum CardCategory {
  BlunderHills = "Blunder Hills",
  YumYumDesert = "Yum Yum Desert",
  EasyResources = "Easy Resources",
  MediumResources = "Medium Resources",
  FrostbiteTundra = "Frostbite Tundra",
  Bosses = "Bosses",
  Events = "Events",
}

export type Card = {
  id: string;
  category: CardCategory;
  effect: Effects;
  base: number;
  source?: string;
};

export const Cards: Card[] = [
  {
    id: "Green_Mushroom",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseHP,
    base: 12,
    source: "Green Mushrooms (1/10,000)",
  },
  {
    id: "Red_Mushroom",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseLUK,
    base: 3,
    source: "Red Mushroom (1/10,000)",
  },
  {
    id: "Frog",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseMP,
    base: 10,
    source: "Frog (1/10,000)",
  },
  {
    id: "Bored_Bean",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseDamage,
    base: 7,
    source: "Bored Bean (1/10,300)",
  },
  {
    id: "Slime",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseWIS,
    base: 2,
    source: "Slime (1/10,500)",
  },
  {
    id: "Baby_Boa",
    category: CardCategory.BlunderHills,
    effect: Effects.MoveSpeed,
    base: 1,
    source: "Baby Boa (1/10,600)",
  },
  {
    id: "Carrotman",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseAGI,
    base: 2,
    source: "Carrotman (1/11,100)",
  },
  {
    id: "Glublin",
    category: CardCategory.BlunderHills,
    effect: Effects.TotalHP,
    base: 2,
    source: "Glublin (1/11,600)",
  },
  {
    id: "Wode_Board",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseSTR,
    base: 2,
    source: "Wode Board (1/12,500)",
  },
  {
    id: "Gigafrog",
    category: CardCategory.BlunderHills,
    effect: Effects.CardChance,
    base: 5,
    source: "Gigafrog (1/14,300)",
  },
  {
    id: "Poop",
    category: CardCategory.BlunderHills,
    effect: Effects.CrystalChance,
    base: 10,
    source: "Poop (1/16,700)",
  },
  {
    id: "Rat",
    category: CardCategory.BlunderHills,
    effect: Effects.CritChance,
    base: 1,
    source: "Rat (1/20,000)",
  },
  {
    id: "Walking_Stick",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseWIS,
    base: 5,
    source: "Walking Stick (1/16,700)",
  },
  {
    id: "Nutto",
    category: CardCategory.BlunderHills,
    effect: Effects.MonsterMoney,
    base: 5,
    source: "Nutto (1/20,000)",
  },
  {
    id: "Crystal_Carrot",
    category: CardCategory.BlunderHills,
    effect: Effects.DropRate,
    base: 5,
    source: "Crystal Carrot (1/100)",
  },
  {
    id: "Wood_Mushroom",
    category: CardCategory.BlunderHills,
    effect: Effects.TotalAccuracy,
    base: 5,
    source: "Wood Mushroom (1/10,000)",
  },
  {
    id: "Sandy_Pot",
    category: CardCategory.YumYumDesert,
    effect: Effects.ExpConversion,
    base: 12,
    source: "Sandy Pot (1/10,000)",
  },
  {
    id: "Mimic",
    category: CardCategory.YumYumDesert,
    effect: Effects.DropRate,
    base: 3,
    source: "Mimic (1/10,000)",
  },
  {
    id: "Crabcake",
    category: CardCategory.YumYumDesert,
    effect: Effects.NoFoodConsume,
    base: 6,
    source: "Crabcake (1/10,000)",
  },
  {
    id: "Mafioso",
    category: CardCategory.YumYumDesert,
    effect: Effects.BaseAGI,
    base: 5,
    source: "Mafioso (1/10,000)",
  },
  {
    id: "Sand_Castle",
    category: CardCategory.YumYumDesert,
    effect: Effects.TotalAccuracy,
    base: 4,
    source: "Sand Castle (1/10,000)",
  },
  {
    id: "Pincermin",
    category: CardCategory.YumYumDesert,
    effect: Effects.WeaponPower,
    base: 1,
    source: "Pincermin (1/10,000)",
  },
  {
    id: "Mashed_Potato",
    category: CardCategory.YumYumDesert,
    effect: Effects.CritDamage,
    base: 3,
    source: "Mashed Potato (1/10,000)",
  },
  {
    id: "Tyson",
    category: CardCategory.YumYumDesert,
    effect: Effects.BaseSTR,
    base: 5,
    source: "Tyson (1/10,000)",
  },
  {
    id: "Moonmoon",
    category: CardCategory.YumYumDesert,
    effect: Effects.MonsterExpActive,
    base: 8,
    source: "Moonmoon (1/10,000)",
  },
  {
    id: "Sand_Giant",
    category: CardCategory.YumYumDesert,
    effect: Effects.MinimumDamage,
    base: 2,
    source: "Sand Giant (1/10,000)",
  },
  {
    id: "Snelbie",
    category: CardCategory.YumYumDesert,
    effect: Effects.CardChance,
    base: 8,
    source: "Snelbie (1/10,000)",
  },
  {
    id: "Dig_Doug",
    category: CardCategory.YumYumDesert,
    effect: Effects.BaseLUK,
    base: 6,
    source: "Dig Doug (1/10,000)",
  },
  {
    id: "Crystal_Crabal",
    category: CardCategory.YumYumDesert,
    effect: Effects.MonsterExp,
    base: 2,
    source: "Crystal Crabal (1/125)",
  },
  {
    id: "Bandit_Bob",
    category: CardCategory.YumYumDesert,
    effect: Effects.MonsterMoney,
    base: 1,
    source: "Survive Bandit Bob",
  },
  {
    id: "Copper_Ore",
    category: CardCategory.EasyResources,
    effect: Effects.BaseAccuracy,
    base: 4,
    source: "Mining Copper",
  },
  {
    id: "Iron_Ore",
    category: CardCategory.EasyResources,
    effect: Effects.MiningEfficiency,
    base: 5,
    source: "Mining Iron",
  },
  {
    id: "Gold_Ore",
    category: CardCategory.EasyResources,
    effect: Effects.MiningExp,
    base: 5,
    source: "Mining Gold",
  },
  {
    id: "Fire_Forge",
    category: CardCategory.EasyResources,
    effect: Effects.SmithingExp,
    base: 4,
    source: "Smelting Ore in Slots 1-4",
  },
  {
    id: "Oak_Logs",
    category: CardCategory.EasyResources,
    effect: Effects.BaseDefense,
    base: 3,
    source: "Choppin Oak Tree",
  },
  {
    id: "Bleach_Logs",
    category: CardCategory.EasyResources,
    effect: Effects.ChoppinEfficiency,
    base: 5,
    source: "Choppin Birch Tree",
  },
  {
    id: "Jungle_Logs",
    category: CardCategory.EasyResources,
    effect: Effects.ChoppinExp,
    base: 5,
    source: "Choppin Jungle Tree",
  },
  {
    id: "Forest_Fibres",
    category: CardCategory.EasyResources,
    effect: Effects.ExpConversion,
    base: 8,
    source: "Choppin Forest Tree",
  },
  {
    id: "Goldfish",
    category: CardCategory.EasyResources,
    effect: Effects.TotalMP,
    base: 3,
    source: "Fishing Goldfish",
  },
  {
    id: "Hermit_Can",
    category: CardCategory.EasyResources,
    effect: Effects.FishingEfficiency,
    base: 5,
    source: "Fishing Hermit Cans",
  },
  {
    id: "Jellyfish",
    category: CardCategory.EasyResources,
    effect: Effects.FishingExp,
    base: 5,
    source: "Fishing Jellyfish",
  },
  {
    id: "Fly",
    category: CardCategory.EasyResources,
    effect: Effects.MonsterExpActive,
    base: 4,
    source: "Catching Flies",
  },
  {
    id: "Butterfly",
    category: CardCategory.EasyResources,
    effect: Effects.CatchingEfficiency,
    base: 5,
    source: "Catching Butterflies",
  },
  {
    id: "Platinum_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.MiningAfk,
    base: 2,
    source: "Mining Platinum",
  },
  {
    id: "Dementia_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.MiningSpeed,
    base: 4,
    source: "Mining Dementia",
  },
  {
    id: "Void_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.CardChance,
    base: 6,
    source: "Mining Void",
  },
  {
    id: "Lustre_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.BaseLUK,
    base: 4,
    source: "Mining Lustre",
  },
  {
    id: "Cinder_Forge",
    category: CardCategory.MediumResources,
    effect: Effects.SmithingExp,
    base: 7,
    source: "Smelting Ore in Slots 5-8",
  },
  {
    id: "Tropilogs",
    category: CardCategory.MediumResources,
    effect: Effects.ChoppinAfk,
    base: 2,
    source: "Choppin Palm Tree",
  },
  {
    id: "Potty_Rolls",
    category: CardCategory.MediumResources,
    effect: Effects.ChoppinSpeed,
    base: 4,
    source: "Choppin Toilet Tree",
  },
  {
    id: "Veiny_Logs",
    category: CardCategory.MediumResources,
    effect: Effects.TotalAccuracy,
    base: 3,
    source: "Choppin Stump Tree",
  },
  {
    id: "Bloach",
    category: CardCategory.MediumResources,
    effect: Effects.FishingAfk,
    base: 2,
    source: "Fishing Bloaches",
  },
  {
    id: "Sentient_Cereal",
    category: CardCategory.MediumResources,
    effect: Effects.CatchingExp,
    base: 5,
    source: "Catching Sentient Cereal",
  },
  {
    id: "Fruitfly",
    category: CardCategory.MediumResources,
    effect: Effects.CatchingAfk,
    base: 2,
    source: "Catching Fruitflies",
  },
  {
    id: "Forest_Soul",
    category: CardCategory.MediumResources,
    effect: Effects.EquipmentDefense,
    base: 3,
    source: "Glublin Totem",
  },
  {
    id: "Dune_Soul",
    category: CardCategory.MediumResources,
    effect: Effects.WorshipCharge,
    base: 3,
    source: "",
  },
  {
    id: "Froge",
    category: CardCategory.MediumResources,
    effect: Effects.TrappingShiny,
    base: 3,
    source: "Trapping Froges",
  },
  {
    id: "Crabbo",
    category: CardCategory.MediumResources,
    effect: Effects.TrappingEfficiency,
    base: 5,
    source: "Trapping Crabbos",
  },
  {
    id: "Scorpie",
    category: CardCategory.MediumResources,
    effect: Effects.TrappingExp,
    base: 5,
    source: "Trapping Scorpies",
  },
  {
    id: "Sheepie",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.EquipmentDefense,
    base: 3,
    source: "1/10000",
  },
  {
    id: "Frost_Flake",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.BaseSTR,
    base: 7,
    source: "1/10000",
  },
  {
    id: "Sir_Stache",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.CardChance,
    base: 8,
    source: "1/10000",
  },
  {
    id: "Bloque",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.BaseAGI,
    base: 7,
    source: "1/10000",
  },
  {
    id: "Mamooth",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.TotalHP,
    base: 3.5,
    source: "1/10000",
  },
  {
    id: "Snowman",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.TotalDamage,
    base: 3,
    source: "1/10000",
  },
  {
    id: "Penguin",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.BaseWIS,
    base: 7,
    source: "1/10000",
  },
  {
    id: "Thermister",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.CritDamage,
    base: 4,
    source: "1/10000",
  },
  {
    id: "Quenchie",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.BaseLUK,
    base: 7,
    source: "1/10000",
  },
  {
    id: "Cryosnake",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.MPRegen,
    base: 5,
    source: "1/10000",
  },
  {
    id: "Bop_Box",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.DropRate,
    base: 3,
    source: "1/10000",
  },
  {
    id: "Neyeptune",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.TotalAccuracy,
    base: 5,
    source: "1/10000",
  },
  {
    id: "Dedotated_Ram",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.WeaponPower,
    base: 2,
    source: "1/10000",
  },
  {
    id: "Xylobone",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.CritChance,
    base: 1,
    source: "1/20",
  },
  {
    id: "BloodBone",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.TotalDamage,
    base: 3,
    source: "1/10000",
  },
  {
    id: "Crystal_Cattle",
    category: CardCategory.FrostbiteTundra,
    effect: Effects.MonsterExp,
    base: 3,
    source: "",
  },
  {
    id: "Baba_Yaga",
    category: CardCategory.Bosses,
    effect: Effects.MonsterMoney,
    base: 10,
    source: "Baba Yaga (1/33.3)",
  },
  {
    id: "Dr._Defecaus",
    category: CardCategory.Bosses,
    effect: Effects.TotalDamage,
    base: 5,
    source: "Dr. Defecaus (1/33.3)",
  },
  {
    id: "Boop",
    category: CardCategory.Bosses,
    effect: Effects.FightingAfk,
    base: 1,
    source: "Boop (1/667)",
  },
  {
    id: "Normal_Amarok",
    category: CardCategory.Bosses,
    effect: Effects.SkillAfk,
    base: 2.5,
    source: "Normal Amarok (1/25)",
  },
  {
    id: "Chaotic_Amarok",
    category: CardCategory.Bosses,
    effect: Effects.FightingAfk,
    base: 2.5,
    source: "Chaotic Amarok (1/50)",
  },
  {
    id: "Biggie_Hours",
    category: CardCategory.Bosses,
    effect: Effects.DoubleAfkChance,
    base: 3,
    source: "Biggie Hours (1/41.7)",
  },
  {
    id: "King_Doot",
    category: CardCategory.Bosses,
    effect: Effects.DropRate,
    base: 6,
    source: "King Doot (1/25)",
  },
  {
    id: "Normal_Efaunt",
    category: CardCategory.Bosses,
    effect: Effects.MonsterExp,
    base: 5,
    source: "Normal Efaunt (1/28.6)",
  },
  {
    id: "Chaotic_Efaunt",
    category: CardCategory.Bosses,
    effect: Effects.SkillExp,
    base: 3.75,
    source: "Chaotic Efaunt (1/50)",
  },
  {
    id: "Chizoar",
    category: CardCategory.Bosses,
    effect: Effects.CogSpeed,
    base: 10,
    source: "",
  },
  {
    id: "Chaotic_Chizoar",
    category: CardCategory.Bosses,
    effect: Effects.ShrineEffect,
    base: 5,
    source: "",
  },
  {
    id: "Ghost",
    category: CardCategory.Events,
    effect: Effects.MonsterExpActive,
    base: 3,
    source: "Ghost (1/20)",
  },
  {
    id: "Giftmas_Blobulyte",
    category: CardCategory.Events,
    effect: Effects.DropRate,
    base: 3,
    source: "Giftmas Box",
  },
  {
    id: "Meaning_of_Giftmas",
    category: CardCategory.Events,
    effect: Effects.MonsterMoney,
    base: 3,
    source: "Giftmas Box",
  },
  {
    id: "Valentslime",
    category: CardCategory.Events,
    effect: Effects.EquipmentDefense,
    base: 3,
    source: "Valentslime (1/11.8)",
  },
  {
    id: "Loveulyte",
    category: CardCategory.Events,
    effect: Effects.TotalHP,
    base: 5,
    source: "Choco Box",
  },
  {
    id: "Choco_Box",
    category: CardCategory.Events,
    effect: Effects.BoostFoodEffect,
    base: 4,
    source: "Choco Box",
  },
  {
    id: "Floofie",
    category: CardCategory.Events,
    effect: Effects.MPRegen,
    base: 3,
    source: "Floofie (1/20)",
  },
  {
    id: "Shell_Snake",
    category: CardCategory.Events,
    effect: Effects.BaseLUK,
    base: 3,
    source: "Shell Snake (1/20)",
  },
  {
    id: "Egggulyte",
    category: CardCategory.Events,
    effect: Effects.CardChance,
    base: 1,
    source: "Egg Capsule",
  },
  {
    id: "Egg_Capsule",
    category: CardCategory.Events,
    effect: Effects.CritDamage,
    base: 1,
    source: "Egg Capsule",
  },
];
