import { Effects } from "./Utilities";

export enum CardCategory {
  BlunderHills = "Blunder Hills",
  YumYumDesert = "Yum Yum Desert",
  FrostbiteTundra = "Frostbite Tundra",
  EasyResources = "Easy Resources",
  MediumResources = "Medium Resources",
  Bosses = "Bosses",
  Events = "Events",
}

export type Card = {
  id: string;
  category: CardCategory;
  effect: Effects;
  base: number;
  source?: string;
};

export const Cards: Card[] = [
  {
    id: "Green_Mushroom",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseHP,
    base: 12,
    source: "Green Mushrooms (1/10,000)",
  },
  {
    id: "Red_Mushroom",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseLUK,
    base: 3,
    source: "Red Mushroom (1/10,000)",
  },
  {
    id: "Frog",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseMP,
    base: 10,
    source: "Frog (1/10,000)",
  },
  {
    id: "Bored_Bean",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseDamage,
    base: 7,
    source: "Bored Bean (1/10,300)",
  },
  {
    id: "Slime",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseWIS,
    base: 2,
    source: "Slime (1/10,500)",
  },
  {
    id: "Baby_Boa",
    category: CardCategory.BlunderHills,
    effect: Effects.MoveSpeed,
    base: 1,
    source: "Baby Boa (1/10,600)",
  },
  {
    id: "Carrotman",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseAGI,
    base: 2,
    source: "Carrotman (1/11,100)",
  },
  {
    id: "Glublin",
    category: CardCategory.BlunderHills,
    effect: Effects.TotalHP,
    base: 2,
    source: "Glublin (1/11,600)",
  },
  {
    id: "Wode_Board",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseSTR,
    base: 2,
    source: "Wode Board (1/12,500)",
  },
  {
    id: "Gigafrog",
    category: CardCategory.BlunderHills,
    effect: Effects.CardChance,
    base: 5,
    source: "Gigafrog (1/14,300)",
  },
  {
    id: "Poop",
    category: CardCategory.BlunderHills,
    effect: Effects.CrystalChance,
    base: 10,
    source: "Poop (1/16,700)",
  },
  {
    id: "Rat",
    category: CardCategory.BlunderHills,
    effect: Effects.CritChance,
    base: 1,
    source: "Rat (1/20,000)",
  },
  {
    id: "Walking_Stick",
    category: CardCategory.BlunderHills,
    effect: Effects.BaseWIS,
    base: 5,
    source: "Walking Stick (1/16,700)",
  },
  {
    id: "Nutto",
    category: CardCategory.BlunderHills,
    effect: Effects.MonsterMoney,
    base: 5,
    source: "Nutto (1/20,000)",
  },
  {
    id: "Crystal_Carrot",
    category: CardCategory.BlunderHills,
    effect: Effects.DropRate,
    base: 5,
    source: "Crystal Carrot (1/100)",
  },
  {
    id: "Wood_Mushroom",
    category: CardCategory.BlunderHills,
    effect: Effects.TotalAccuracy,
    base: 5,
    source: "Wood Mushroom (1/10,000)",
  },
  {
    id: "Sandy_Pot",
    category: CardCategory.YumYumDesert,
    effect: Effects.ExpConversion,
    base: 12,
    source: "Sandy Pot (1/10,000)",
  },
  {
    id: "Mimic",
    category: CardCategory.YumYumDesert,
    effect: Effects.DropRate,
    base: 3,
    source: "Mimic (1/10,000)",
  },
  {
    id: "Crabcake",
    category: CardCategory.YumYumDesert,
    effect: Effects.NoFoodConsume,
    base: 6,
    source: "Crabcake (1/10,000)",
  },
  {
    id: "Mafioso",
    category: CardCategory.YumYumDesert,
    effect: Effects.BaseAGI,
    base: 5,
    source: "Mafioso (1/10,000)",
  },
  {
    id: "Sand_Castle",
    category: CardCategory.YumYumDesert,
    effect: Effects.TotalAccuracy,
    base: 4,
    source: "Sand_Castle (1/10,000)",
  },
  {
    id: "Pincermin",
    category: CardCategory.YumYumDesert,
    effect: Effects.WeaponPower,
    base: 1,
    source: "Pincermin (1/10,000)",
  },
  {
    id: "Mashed_Potato",
    category: CardCategory.YumYumDesert,
    effect: Effects.CritDamage,
    base: 3,
    source: "Mashed_Potato (1/10,000)",
  },
  {
    id: "Tyson",
    category: CardCategory.YumYumDesert,
    effect: Effects.BaseSTR,
    base: 5,
    source: "Tyson (1/10,000)",
  },
  {
    id: "Moonmoon",
    category: CardCategory.YumYumDesert,
    effect: Effects.MonsterExpActive,
    base: 8,
    source: "Moonmoon (1/10,000)",
  },
  {
    id: "Sand_Giant",
    category: CardCategory.YumYumDesert,
    effect: Effects.MinimumDamage,
    base: 2,
    source: "Sand_Giant (1/10,000)",
  },
  {
    id: "Snelbie",
    category: CardCategory.YumYumDesert,
    effect: Effects.CardChance,
    base: 8,
    source: "Snelbie (1/10,000)",
  },
  {
    id: "Dig_Doug",
    category: CardCategory.YumYumDesert,
    effect: Effects.BaseLUK,
    base: 6,
    source: "Dig_Doug (1/10,000)",
  },
  {
    id: "Crystal_Crabal",
    category: CardCategory.YumYumDesert,
    effect: Effects.MonsterExp,
    base: 2,
    source: "Crystal_Crabal (1/125)",
  },
  {
    id: "Bandit_Bob",
    category: CardCategory.YumYumDesert,
    effect: Effects.MonsterMoney,
    base: 1,
    source: "Survive Bandit Bob",
  },
  {
    id: "Copper_Ore",
    category: CardCategory.EasyResources,
    effect: Effects.BaseAccuracy,
    base: 1,
    source: "",
  },
  {
    id: "Iron_Ore",
    category: CardCategory.EasyResources,
    effect: Effects.MiningEfficiency,
    base: 5,
    source: "",
  },
  {
    id: "Gold_Ore",
    category: CardCategory.EasyResources,
    effect: Effects.MiningExp,
    base: 5,
    source: "",
  },
  {
    id: "Fire_Forge",
    category: CardCategory.EasyResources,
    effect: Effects.SmithingExp,
    base: 4,
    source: "",
  },
  {
    id: "Oak_Logs",
    category: CardCategory.EasyResources,
    effect: Effects.BaseDefense,
    base: 3,
    source: "",
  },
  {
    id: "Bleach_Logs",
    category: CardCategory.EasyResources,
    effect: Effects.ChoppinEfficiency,
    base: 5,
    source: "",
  },
  {
    id: "Jungle_Logs",
    category: CardCategory.EasyResources,
    effect: Effects.ChoppinExp,
    base: 5,
    source: "",
  },
  {
    id: "Forest_Fibres",
    category: CardCategory.EasyResources,
    effect: Effects.ExpConversion,
    base: 8,
    source: "",
  },
  {
    id: "Goldfish",
    category: CardCategory.EasyResources,
    effect: Effects.TotalMP,
    base: 3,
    source: "",
  },
  {
    id: "Hermit_Can",
    category: CardCategory.EasyResources,
    effect: Effects.FishingEfficiency,
    base: 5,
    source: "",
  },
  {
    id: "Jellyfish",
    category: CardCategory.EasyResources,
    effect: Effects.FishingExp,
    base: 5,
    source: "",
  },
  {
    id: "Fly",
    category: CardCategory.EasyResources,
    effect: Effects.MonsterExpActive,
    base: 4,
    source: "",
  },
  {
    id: "Butterfly",
    category: CardCategory.EasyResources,
    effect: Effects.CatchingEfficiency,
    base: 5,
    source: "",
  },
  {
    id: "Platinum_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.MiningAfk,
    base: 2,
    source: "",
  },
  {
    id: "Dementia_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.MiningSpeed,
    base: 4,
    source: "",
  },
  {
    id: "Void_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.CardChance,
    base: 6,
    source: "",
  },
  {
    id: "Lustre_Ore",
    category: CardCategory.MediumResources,
    effect: Effects.BaseLUK,
    base: 4,
    source: "",
  },
  {
    id: "Cinder_Forge",
    category: CardCategory.MediumResources,
    effect: Effects.SmithingExp,
    base: 7,
    source: "",
  },
  {
    id: "Tropilogs",
    category: CardCategory.MediumResources,
    effect: Effects.ChoppinAfk,
    base: 2,
    source: "",
  },
  {
    id: "Potty_Rolls",
    category: CardCategory.MediumResources,
    effect: Effects.ChoppinSpeed,
    base: 4,
    source: "",
  },
  {
    id: "Veiny_Logs",
    category: CardCategory.MediumResources,
    effect: Effects.TotalAccuracy,
    base: 3,
    source: "",
  },
  {
    id: "Bloach",
    category: CardCategory.MediumResources,
    effect: Effects.FishingAfk,
    base: 2,
    source: "",
  },
  {
    id: "Sentient_Cereal",
    category: CardCategory.MediumResources,
    effect: Effects.CatchingExp,
    base: 5,
    source: "",
  },
  {
    id: "Fruitfly",
    category: CardCategory.MediumResources,
    effect: Effects.CatchingAfk,
    base: 2,
    source: "",
  },
  {
    id: "Baba_Yaga",
    category: CardCategory.Bosses,
    effect: Effects.MonsterMoney,
    base: 10,
    source: "Baba Yaga (1/33.3)",
  },
  {
    id: "Dr._Defecaus",
    category: CardCategory.Bosses,
    effect: Effects.TotalDamage,
    base: 5,
    source: "Dr. Defecaus (1/33.3)",
  },
  {
    id: "Boop",
    category: CardCategory.Bosses,
    effect: Effects.FightingAfk,
    base: 1,
    source: "Boop (1/667)",
  },
  {
    id: "Normal_Amarok",
    category: CardCategory.Bosses,
    effect: Effects.SkillAfk,
    base: 2.5,
    source: "Normal_Amarok (1/25)",
  },
  {
    id: "Chaotic_Amarok",
    category: CardCategory.Bosses,
    effect: Effects.FightingAfk,
    base: 2.5,
    source: "Chaotic_Amarok (1/50)",
  },
  {
    id: "Normal_Efaunt",
    category: CardCategory.Bosses,
    effect: Effects.MonsterExp,
    base: 5,
    source: "Normal_Efaunt (1/28.6)",
  },
  {
    id: "Biggie_Hours",
    category: CardCategory.Bosses,
    effect: Effects.DoubleAfkChance,
    base: 3,
    source: "Biggie_Hours (1/41.7)",
  },
  {
    id: "King_Doot",
    category: CardCategory.Bosses,
    effect: Effects.DropRate,
    base: 6,
    source: "King_Doot (1/25)",
  },
  {
    id: "Chaotic_Efaunt",
    category: CardCategory.Bosses,
    effect: Effects.SkillExp,
    base: 3.75,
    source: "",
  },
  {
    id: "Ghost_(Event)",
    category: CardCategory.Events,
    effect: Effects.MonsterExpActive,
    base: 3,
    source: "Ghost_(Event) (1/20)",
  },
  {
    id: "Giftmas_Blobulyte",
    category: CardCategory.Events,
    effect: Effects.DropRate,
    base: 3,
    source: "",
  },
  {
    id: "Meaning_of_Giftmas",
    category: CardCategory.Events,
    effect: Effects.MonsterMoney,
    base: 3,
    source: "",
  },
  {
    id: "Valentslime",
    category: CardCategory.Events,
    effect: Effects.EquipmentDefense,
    base: 3,
    source: "Valentslime (1/11.8)",
  },
  {
    id: "Loveulyte",
    category: CardCategory.Events,
    effect: Effects.TotalHP,
    base: 5,
    source: "",
  },
  {
    id: "Chocco_Box",
    category: CardCategory.Events,
    effect: Effects.BoostFoodEffect,
    base: 4,
    source: "",
  },
  {
    id: "Floofie",
    category: CardCategory.Events,
    effect: Effects.MPRegen,
    base: 3,
    source: "",
  },
  {
    id: "Shell_Snake",
    category: CardCategory.Events,
    effect: Effects.BaseLUK,
    base: 3,
    source: "",
  },
  {
    id: "Egggulyte",
    category: CardCategory.Events,
    effect: Effects.CardChance,
    base: 1,
    source: "",
  },
  {
    id: "Egg_Capsule",
    category: CardCategory.Events,
    effect: Effects.CritDamage,
    base: 1,
    source: "",
  },
];
