import { Class, EquipmentType, Equippable } from "~/composables/Characters";

export function useEquipment() {
  const getEquipmentByType = (type: EquipmentType) => {
    return AllEquipment.filter((x) => x.type === type);
  };

  const getEmptyEquipment = (type: EquipmentType) => {
    const name = type === EquipmentType.Nothing ? "Empty" : `No_${type}`;
    return {
      name,
      type,
      class: Class.Beginner,
      weaponPower: 0,
      speed: 0,
      defense: 0,
      strength: 0,
      agility: 0,
      wisdom: 0,
      luck: 0,
      reach: 0,
      miscellaneous: [],
    };
  };

  return {
    getEmptyEquipment,
    getEquipmentByType,
  };
}

// ALL EQUIPMENT DATA
export const AllEquipment: Equippable[] = [
  {
    name: "No_Weapon",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Shirt",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Pants",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Shoes",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Pendant",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Ring",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Axe",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Fishing_Rod",
    type: EquipmentType.Fishing_Rod,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Catching_Net",
    type: EquipmentType.Catching_Net,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Trap_Box",
    type: EquipmentType.Trap_Box,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Worship_Skull",
    type: EquipmentType.Worship_Skull,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Premium_Helmet",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Premium_Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "No_Trophy",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    weaponPower: 0,
    speed: 0,
    defense: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    reach: 0,
    miscellaneous: [],
  },
  {
    name: "Farmer Brim",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 0,
    defense: 2,
    miscellaneous: [],
  },
  {
    name: "Mark of Member",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 20,
    defense: 50,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 15,
      },
    ],
  },
  {
    name: "Leather Cap",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 2,
    wisdom: 2,
    luck: 0,
    defense: 4,
    miscellaneous: [],
  },
  {
    name: "White Headband",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Green Headband",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 4,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Red Headband",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 1,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Purple Tupacband",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 2,
    wisdom: 5,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Yellow Headband",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 2,
    wisdom: 3,
    luck: 8,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Traffic Cone",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Propeller Cap",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 1,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Baseball Hat",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Stump Prop",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 5,
    strength: 0,
    agility: 3,
    wisdom: 0,
    luck: 4,
    defense: 2,
    miscellaneous: [
      {
        effect: "% Total Choppin Efficiency",
        value: 5,
      },
    ],
  },
  {
    name: "Copper Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 0,
    defense: 5,
    miscellaneous: [],
  },
  {
    name: "Iron Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 5,
    agility: 5,
    wisdom: 5,
    luck: 0,
    defense: 9,
    miscellaneous: [],
  },
  {
    name: "Gold Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 7,
    agility: 7,
    wisdom: 7,
    luck: 0,
    defense: 15,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 3,
      },
    ],
  },
  {
    name: "Amarok Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 4,
    agility: 4,
    wisdom: 4,
    luck: 4,
    defense: 20,
    miscellaneous: [],
  },
  {
    name: "Platinum Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 9,
    agility: 9,
    wisdom: 9,
    luck: 0,
    defense: 25,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 5,
      },
    ],
  },
  {
    name: "Dementia Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 12,
    agility: 12,
    wisdom: 12,
    luck: 12,
    defense: 34,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 6,
      },
    ],
  },
  {
    name: "Efaunt Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 8,
    agility: 8,
    wisdom: 8,
    luck: 8,
    defense: 38,
    miscellaneous: [
      {
        effect: "% Total Drop Rate",
        value: 5,
      },
    ],
  },
  {
    name: "Void Imperium Helmet",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 15,
    agility: 15,
    wisdom: 15,
    luck: 15,
    defense: 46,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 8,
      },
    ],
  },
  {
    name: "Party Hat",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 5,
    defense: 10,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 5,
      },
    ],
  },
  {
    name: "Bored Beanie",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 7,
    wisdom: 0,
    luck: 3,
    defense: 5,
    miscellaneous: [],
  },
  {
    name: "Royal Turban",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 15,
    wisdom: 0,
    luck: 0,
    defense: 7,
    miscellaneous: [
      {
        effect: "% Gold Food Effect",
        value: 15,
      },
    ],
  },
  {
    name: "Alien Headband",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 3,
    wisdom: 11,
    luck: 0,
    defense: 4,
    miscellaneous: [
      {
        effect: "% MP Regen Rate",
        value: 10,
      },
    ],
  },
  {
    name: "Cowbo Galloneer",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 3,
    miscellaneous: [
      {
        effect: "Base Damage",
        value: 25,
      },
    ],
  },
  {
    name: "Grandma Disguise",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 15,
    luck: 0,
    defense: 5,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 7,
      },
    ],
  },
  {
    name: "Santa Hat",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 5,
      },
    ],
  },
  {
    name: "Jar",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 25,
    miscellaneous: [],
  },
  {
    name: "Big Pretty Bow",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 5,
      },
    ],
  },
  {
    name: "Steam Cap",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 3,
      },
    ],
  },
  {
    name: "Bunny Ears",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 4,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 4,
      },
    ],
  },
  {
    name: "Summer Shell",
    type: EquipmentType.Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 4,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 4,
      },
    ],
  },
  {
    name: "Militia Helm",
    type: EquipmentType.Helmet,
    class: Class.Warrior,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 7,
    agility: 2,
    wisdom: 0,
    luck: 0,
    defense: 11,
    miscellaneous: [],
  },
  {
    name: "Viking Cap",
    type: EquipmentType.Helmet,
    class: Class.Warrior,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 13,
    agility: 0,
    wisdom: 3,
    luck: 0,
    defense: 21,
    miscellaneous: [
      {
        effect: "% Total Mining Efficiency",
        value: 10,
      },
    ],
  },
  {
    name: "Murmillo Helm",
    type: EquipmentType.Helmet,
    class: Class.Warrior,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 20,
    agility: 0,
    wisdom: 10,
    luck: 0,
    defense: 55,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 10,
      },
    ],
  },
  {
    name: "Thief Hood",
    type: EquipmentType.Helmet,
    class: Class.Archer,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 6,
    wisdom: 0,
    luck: 0,
    defense: 9,
    miscellaneous: [],
  },
  {
    name: "Sleek Coif",
    type: EquipmentType.Helmet,
    class: Class.Archer,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 4,
    agility: 12,
    wisdom: 0,
    luck: 0,
    defense: 18,
    miscellaneous: [],
  },
  {
    name: "Conquistador Plume",
    type: EquipmentType.Helmet,
    class: Class.Archer,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 7,
    agility: 23,
    wisdom: 0,
    luck: 0,
    defense: 47,
    miscellaneous: [
      {
        effect: "% Movement Speed",
        value: 6,
      },
    ],
  },
  {
    name: "Top Hat",
    type: EquipmentType.Helmet,
    class: Class.Mage,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 8,
    luck: 1,
    defense: 7,
    miscellaneous: [],
  },
  {
    name: "Witch Hat",
    type: EquipmentType.Helmet,
    class: Class.Mage,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 1,
    wisdom: 16,
    luck: 0,
    defense: 15,
    miscellaneous: [
      {
        effect: "% Total Choppin Efficiency",
        value: 10,
      },
    ],
  },
  {
    name: "Adornment of the High Priest",
    type: EquipmentType.Helmet,
    class: Class.Mage,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 0,
    agility: 5,
    wisdom: 25,
    luck: 0,
    defense: 40,
    miscellaneous: [
      {
        effect: "% Crit Damage",
        value: 30,
      },
    ],
  },
  {
    name: "Boxing Gloves",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 5,
    reach: 55,
    weaponPower: 4,
    strength: 2,
    agility: 0,
    wisdom: 0,
    luck: 2,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "The Stingers",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 5,
    reach: 60,
    weaponPower: 11,
    strength: 5,
    agility: 0,
    wisdom: 0,
    luck: 5,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Bandage Wraps",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 7,
    reach: 65,
    weaponPower: 20,
    strength: 6,
    agility: 0,
    wisdom: 0,
    luck: 10,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Uninflated Glove",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 8,
    reach: 65,
    weaponPower: 27,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 13,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Eclectic Ordeal",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 9,
    reach: 85,
    weaponPower: 32,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 17,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Crit Chance",
        value: 5,
      },
    ],
  },
  {
    name: "Wooden Spear",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 5,
    reach: 70,
    weaponPower: 7,
    strength: 3,
    agility: 0,
    wisdom: 1,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Steel Axe",
    type: EquipmentType.Weapon,
    class: Class.Warrior,
    speed: 5,
    reach: 62,
    weaponPower: 14,
    strength: 7,
    agility: 0,
    wisdom: 3,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Royal Bayonet",
    type: EquipmentType.Weapon,
    class: Class.Warrior,
    speed: 5,
    reach: 95,
    weaponPower: 20,
    strength: 10,
    agility: 0,
    wisdom: 2,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Enforced Slasher",
    type: EquipmentType.Weapon,
    class: Class.Warrior,
    speed: 5,
    reach: 80,
    weaponPower: 26,
    strength: 11,
    agility: 0,
    wisdom: 4,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "The Ice Breaker",
    type: EquipmentType.Weapon,
    class: Class.Warrior,
    speed: 5,
    reach: 76,
    weaponPower: 33,
    strength: 13,
    agility: 0,
    wisdom: 6,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Crit Damage",
        value: 5,
      },
    ],
  },
  {
    name: "Deuscythe",
    type: EquipmentType.Weapon,
    class: Class.Warrior,
    speed: 6,
    reach: 88,
    weaponPower: 40,
    strength: 20,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Crit Damage",
        value: 5,
      },
    ],
  },
  {
    name: "Wooden Bow",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 5,
    reach: 150,
    weaponPower: 7,
    strength: 2,
    agility: 3,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Birch Longbow",
    type: EquipmentType.Weapon,
    class: Class.Archer,
    speed: 6,
    reach: 170,
    weaponPower: 12,
    strength: 4,
    agility: 5,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Carrot Launcher",
    type: EquipmentType.Weapon,
    class: Class.Archer,
    speed: 2,
    reach: 225,
    weaponPower: 22,
    strength: 0,
    agility: 8,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Spiked Menace",
    type: EquipmentType.Weapon,
    class: Class.Archer,
    speed: 6,
    reach: 175,
    weaponPower: 17,
    strength: 5,
    agility: 8,
    wisdom: 0,
    luck: 3,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Pharoah Bow",
    type: EquipmentType.Weapon,
    class: Class.Archer,
    speed: 6,
    reach: 200,
    weaponPower: 23,
    strength: 1,
    agility: 13,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Blizzard Bow",
    type: EquipmentType.Weapon,
    class: Class.Archer,
    speed: 6,
    reach: 205,
    weaponPower: 30,
    strength: 0,
    agility: 15,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Crit Damage",
        value: 5,
      },
    ],
  },
  {
    name: "Blackhole Bow",
    type: EquipmentType.Weapon,
    class: Class.Archer,
    speed: 7,
    reach: 230,
    weaponPower: 36,
    strength: 10,
    agility: 13,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Crit Damage",
        value: 5,
      },
    ],
  },
  {
    name: "Gnarled Wand",
    type: EquipmentType.Weapon,
    class: Class.Beginner,
    speed: 5,
    reach: 115,
    weaponPower: 7,
    strength: 0,
    agility: 0,
    wisdom: 4,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Quarterstaff",
    type: EquipmentType.Weapon,
    class: Class.Mage,
    speed: 4,
    reach: 120,
    weaponPower: 16,
    strength: 0,
    agility: 0,
    wisdom: 9,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Starlight",
    type: EquipmentType.Weapon,
    class: Class.Mage,
    speed: 4,
    reach: 145,
    weaponPower: 23,
    strength: 0,
    agility: 1,
    wisdom: 11,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Crows Nest",
    type: EquipmentType.Weapon,
    class: Class.Mage,
    speed: 5,
    reach: 160,
    weaponPower: 30,
    strength: 0,
    agility: 5,
    wisdom: 9,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Movement Speed",
        value: 5,
      },
    ],
  },
  {
    name: "Spriggly Storm",
    type: EquipmentType.Weapon,
    class: Class.Mage,
    speed: 5,
    reach: 155,
    weaponPower: 36,
    strength: 0,
    agility: 0,
    wisdom: 15,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Crit Damage",
        value: 5,
      },
    ],
  },
  {
    name: "Grey Gatsby",
    type: EquipmentType.Weapon,
    class: Class.Mage,
    speed: 6,
    reach: 170,
    weaponPower: 43,
    strength: 0,
    agility: 10,
    wisdom: 13,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Crit Damage",
        value: 5,
      },
    ],
  },
  {
    name: "Orange Tee",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 1,
    wisdom: 0,
    luck: 0,
    defense: 3,
    miscellaneous: [],
  },
  {
    name: "Blue Tee",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 1,
    wisdom: 2,
    luck: 0,
    defense: 3,
    miscellaneous: [],
  },
  {
    name: "Black Tee",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 5,
    miscellaneous: [],
  },
  {
    name: "Tattered Cloth",
    type: EquipmentType.Shirt,
    class: Class.Mage,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 8,
    luck: 3,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Fur Shirt",
    type: EquipmentType.Shirt,
    class: Class.Archer,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 5,
    agility: 9,
    wisdom: 0,
    luck: 0,
    defense: 13,
    miscellaneous: [],
  },
  {
    name: "Copper Platebody",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 2,
    wisdom: 2,
    luck: 0,
    defense: 7,
    miscellaneous: [],
  },
  {
    name: "Iron Platebody",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 0,
    defense: 12,
    miscellaneous: [],
  },
  {
    name: "Gold Platebody",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 5,
    agility: 5,
    wisdom: 5,
    luck: 0,
    defense: 18,
    miscellaneous: [],
  },
  {
    name: "Amarok Bodyplate",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 0,
    defense: 22,
    miscellaneous: [],
  },
  {
    name: "Platinum Platbody",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 8,
    agility: 8,
    wisdom: 8,
    luck: 0,
    defense: 25,
    miscellaneous: [],
  },
  {
    name: "Dementia Body",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 10,
    agility: 10,
    wisdom: 10,
    luck: 0,
    defense: 35,
    miscellaneous: [],
  },
  {
    name: "Efaunt Ribcage",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 5,
    agility: 5,
    wisdom: 5,
    luck: 0,
    defense: 30,
    miscellaneous: [
      {
        effect: "% Mastery",
        value: 4,
      },
    ],
  },
  {
    name: "Void Imperium Platebody",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 13,
    agility: 13,
    wisdom: 13,
    luck: 0,
    defense: 45,
    miscellaneous: [],
  },
  {
    name: "MCR Tshirt",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 2,
    strength: 0,
    agility: 8,
    wisdom: 0,
    luck: 0,
    defense: 1,
    miscellaneous: [],
  },
  {
    name: "Planktop",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 6,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 4,
    miscellaneous: [],
  },
  {
    name: "Hide Shirt",
    type: EquipmentType.Shirt,
    class: Class.Warrior,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 6,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 4,
    miscellaneous: [],
  },
  {
    name: "Green Tee",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 3,
    defense: 4,
    miscellaneous: [],
  },
  {
    name: "Purple Tee",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 3,
    luck: 0,
    defense: 3,
    miscellaneous: [],
  },
  {
    name: "Member Hoodie",
    type: EquipmentType.Shirt,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 25,
    defense: 40,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 15,
      },
    ],
  },
  {
    name: "Studded Hide",
    type: EquipmentType.Shirt,
    class: Class.Warrior,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 10,
    agility: 0,
    wisdom: 4,
    luck: 0,
    defense: 22,
    miscellaneous: [
      {
        effect: "% Total Fishing Efficiency",
        value: 10,
      },
    ],
  },
  {
    name: "Feral Leathering",
    type: EquipmentType.Shirt,
    class: Class.Archer,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 12,
    wisdom: 0,
    luck: 0,
    defense: 18,
    miscellaneous: [
      {
        effect: "% Total Catching Efficiency",
        value: 10,
      },
    ],
  },
  {
    name: "Furled Robes",
    type: EquipmentType.Shirt,
    class: Class.Mage,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 1,
    wisdom: 13,
    luck: 0,
    defense: 14,
    miscellaneous: [],
  },
  {
    name: "Damascus Plates",
    type: EquipmentType.Shirt,
    class: Class.Warrior,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 17,
    agility: 0,
    wisdom: 5,
    luck: 0,
    defense: 52,
    miscellaneous: [],
  },
  {
    name: "Evergreen Wraps",
    type: EquipmentType.Shirt,
    class: Class.Archer,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 4,
    agility: 19,
    wisdom: 0,
    luck: 0,
    defense: 49,
    miscellaneous: [],
  },
  {
    name: "Elegantine Robes",
    type: EquipmentType.Shirt,
    class: Class.Mage,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 1,
    wisdom: 23,
    luck: 0,
    defense: 47,
    miscellaneous: [],
  },
  {
    name: "Torn Jeans",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 2,
    wisdom: 1,
    luck: 0,
    defense: 4,
    miscellaneous: [],
  },
  {
    name: "Copper Platelegs",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 2,
    wisdom: 2,
    luck: 0,
    defense: 6,
    miscellaneous: [],
  },
  {
    name: "Iron Platelegs",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 0,
    defense: 11,
    miscellaneous: [],
  },
  {
    name: "Gold Platelegs",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 4,
    agility: 4,
    wisdom: 4,
    luck: 0,
    defense: 16,
    miscellaneous: [],
  },
  {
    name: "Amarok Hinds",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 2,
    wisdom: 2,
    luck: 0,
    defense: 18,
    miscellaneous: [],
  },
  {
    name: "Platinum Shins",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 6,
    agility: 6,
    wisdom: 6,
    luck: 0,
    defense: 23,
    miscellaneous: [],
  },
  {
    name: "Dementia Shins",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 7,
    agility: 7,
    wisdom: 7,
    luck: 0,
    defense: 28,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 3,
      },
    ],
  },
  {
    name: "Efaunt Hipilium",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 4,
    agility: 4,
    wisdom: 4,
    luck: 0,
    defense: 32,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 5,
      },
    ],
  },
  {
    name: "Void Imperium Shardshins",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 9,
    agility: 9,
    wisdom: 9,
    luck: 0,
    defense: 38,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 7,
      },
    ],
  },
  {
    name: "Give Up On Life Pants",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 6,
    luck: 0,
    defense: 3,
    miscellaneous: [],
  },
  {
    name: "Bleached Designer Wode Patch Pants",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 3,
    wisdom: 7,
    luck: 0,
    defense: 11,
    miscellaneous: [
      {
        effect: "% Total Choppin Efficiency",
        value: 5,
      },
    ],
  },
  {
    name: "Adam's Leaf",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 4,
    agility: 0,
    wisdom: 13,
    luck: 0,
    defense: 2,
    miscellaneous: [],
  },
  {
    name: "Dirty Coal Miner Baggy Soot Pants",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 7,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 12,
    miscellaneous: [
      {
        effect: "% Total Mining Efficiency",
        value: 5,
      },
    ],
  },
  {
    name: "Trimmed Rune Platelegs",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 4,
    agility: 2,
    wisdom: 0,
    luck: 0,
    defense: 20,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 10,
      },
    ],
  },
  {
    name: "Fishing Overalls",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 8,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 15,
    miscellaneous: [
      {
        effect: "% Total Fishing Efficiency",
        value: 12,
      },
    ],
  },
  {
    name: "Bandito Pantaloon",
    type: EquipmentType.Pants,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 9,
    wisdom: 0,
    luck: 0,
    defense: 14,
    miscellaneous: [
      {
        effect: "% Total Catching Efficiency",
        value: 12,
      },
    ],
  },
  {
    name: "Copper Boots",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 2,
    defense: 2,
    miscellaneous: [],
  },
  {
    name: "Iron Boots",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 2,
    wisdom: 2,
    luck: 0,
    defense: 4,
    miscellaneous: [],
  },
  {
    name: "Gold Boots",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 3,
    defense: 8,
    miscellaneous: [],
  },
  {
    name: "Amarok Paws",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 0,
    defense: 10,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 3,
      },
    ],
  },
  {
    name: "Platinum Boots",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 5,
    agility: 5,
    wisdom: 5,
    luck: 5,
    defense: 15,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 5,
      },
    ],
  },
  {
    name: "Dementia Boots",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 7,
    agility: 7,
    wisdom: 7,
    luck: 7,
    defense: 22,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 7,
      },
    ],
  },
  {
    name: "Efaunts Broken Ankles",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 2,
    wisdom: 2,
    luck: 0,
    defense: 18,
    miscellaneous: [
      {
        effect: "% Movement Speed",
        value: 2,
      },
    ],
  },
  {
    name: "Void Imperium Kicks",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 9,
    agility: 9,
    wisdom: 9,
    luck: 9,
    defense: 30,
    miscellaneous: [
      {
        effect: "% Defense",
        value: 8,
      },
    ],
  },
  {
    name: "Goo Galoshes",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 2,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Money from Monsters",
        value: 5,
      },
    ],
  },
  {
    name: "Flip Flops",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 3,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Movement Speed",
        value: 2,
      },
    ],
  },
  {
    name: "Cavern Trekkers",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 5,
    agility: 0,
    wisdom: 1,
    luck: 0,
    defense: 10,
    miscellaneous: [
      {
        effect: "% Total Mining Efficiency",
        value: 20,
      },
    ],
  },
  {
    name: "Logger Heels",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 7,
    luck: 0,
    defense: 6,
    miscellaneous: [
      {
        effect: "% Total Choppin Efficiency",
        value: 20,
      },
    ],
  },
  {
    name: "Angler Boots",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 6,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 8,
    miscellaneous: [
      {
        effect: "% Total Fishing Efficiency",
        value: 20,
      },
    ],
  },
  {
    name: "Bandito Boots",
    type: EquipmentType.Shoes,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 6,
    wisdom: 0,
    luck: 0,
    defense: 8,
    miscellaneous: [
      {
        effect: "% Total Catching Efficiency",
        value: 20,
      },
    ],
  },
  {
    name: "Little Wooden Katana",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 1,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Sleek Shank",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 4,
    miscellaneous: [],
  },
  {
    name: "Carrot Horror",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 2,
    wisdom: 5,
    luck: 2,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Tarantulight",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 2,
    agility: 2,
    wisdom: 2,
    luck: 5,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Fuscismatia",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 10,
    luck: 0,
    defense: 5,
    miscellaneous: [
      {
        effect: "Fishing Purple Depth",
        value: 30,
      },
    ],
  },
  {
    name: "Strung Bludgeon",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 4,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Chaotic Amarok Pendant",
    type: EquipmentType.Pendant,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 2,
    strength: 0,
    agility: 0,
    wisdom: 12,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Copper Band",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 3,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Steel Band",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 4,
    defense: 1,
    miscellaneous: [],
  },
  {
    name: "Death Wish",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 4,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 6,
    miscellaneous: [
      {
        effect: "% Boss Damage",
        value: 5,
      },
    ],
  },
  {
    name: "Pugilist Demise",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Boss Damage",
        value: 4,
      },
    ],
  },
  {
    name: "Defenders Dignity",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 15,
    miscellaneous: [],
  },
  {
    name: "Frisbee Ring",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 12,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "Accuracy",
        value: 20,
      },
    ],
  },
  {
    name: "Silver Stopwatch",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Fighting AFK Gain Rate",
        value: 2,
      },
    ],
  },
  {
    name: "Dooble Goopi",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 1,
    defense: 2,
    miscellaneous: [
      {
        effect: "% Money from Monsters",
        value: 5,
      },
    ],
  },
  {
    name: "Sanic Ring",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 8,
    wisdom: 0,
    luck: 4,
    defense: 5,
    miscellaneous: [
      {
        effect: "% Movement Speed",
        value: 1,
      },
    ],
  },
  {
    name: "Efaunt Trunculus",
    type: EquipmentType.Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 3,
    strength: 0,
    agility: 10,
    wisdom: 0,
    luck: 0,
    defense: 8,
    miscellaneous: [
      {
        effect: "% Crit Chance",
        value: 2,
      },
    ],
  },
  {
    name: "Love Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Love",
        value: 69,
      },
    ],
  },
  {
    name: "Leafy Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% All Natural",
        value: 100,
      },
    ],
  },
  {
    name: "Wealth Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 3,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Coolness",
        value: 777,
      },
    ],
  },
  {
    name: "Bob Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Bob",
        value: 808,
      },
    ],
  },
  {
    name: "Bubble Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Pop Chance",
        value: 0,
      },
    ],
  },
  {
    name: "Cthulu's Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Pure Evil",
        value: 666,
      },
    ],
  },
  {
    name: "Lava Sez Buy More Gems",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Self Esteem",
        value: -1,
      },
    ],
  },
  {
    name: "HONK Ring",
    type: EquipmentType.Premium_Ring,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% HONK",
        value: 100,
      },
    ],
  },
  {
    name: "Junk Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 3,
    reach: 0,
    weaponPower: 2,
    strength: 1,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Copper Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 3,
    reach: 0,
    weaponPower: 6,
    strength: 3,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Iron Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 10,
    strength: 5,
    agility: 2,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Gold Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 13,
    strength: 8,
    agility: 3,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Platinum Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 16,
    strength: 11,
    agility: 4,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Total Mining Efficiency",
        value: 1,
      },
    ],
  },
  {
    name: "Dementia Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 19,
    strength: 15,
    agility: 5,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Total Mining Efficiency",
        value: 2,
      },
    ],
  },
  {
    name: "Void Imperium Pik",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 24,
    strength: 18,
    agility: 6,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Total Mining Efficiency",
        value: 8,
      },
    ],
  },
  {
    name: "Poopy Pickaxe",
    type: EquipmentType.Pickaxe,
    class: Class.Beginner,
    speed: 2,
    reach: 0,
    weaponPower: 18,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 3,
    miscellaneous: [
      {
        effect: "% Total Mining Efficiency",
        value: 2,
      },
    ],
  },
  {
    name: "Old Hatchet",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 3,
    reach: 0,
    weaponPower: 3,
    strength: 0,
    agility: 0,
    wisdom: 1,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Copper Chopper",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 3,
    reach: 0,
    weaponPower: 7,
    strength: 0,
    agility: 1,
    wisdom: 3,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Iron Hatchet",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 3,
    reach: 0,
    weaponPower: 10,
    strength: 2,
    agility: 0,
    wisdom: 5,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Stinky Axe",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 2,
    reach: 0,
    weaponPower: 19,
    strength: 0,
    agility: 0,
    wisdom: 8,
    luck: 4,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Golden Axe",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 14,
    strength: 0,
    agility: 0,
    wisdom: 8,
    luck: 4,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Plat Hatchet",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 18,
    strength: 0,
    agility: 5,
    wisdom: 14,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Dementia Dicer",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 23,
    strength: 0,
    agility: 6,
    wisdom: 17,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Void Imperium Axe",
    type: EquipmentType.Axe,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 26,
    strength: 7,
    agility: 0,
    wisdom: 20,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Copper Fish Rod",
    type: EquipmentType.Fishing_Rod,
    class: Class.Beginner,
    speed: 3,
    reach: 0,
    weaponPower: 8,
    strength: 2,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Iron Fishing Rod",
    type: EquipmentType.Fishing_Rod,
    class: Class.Beginner,
    speed: 3,
    reach: 0,
    weaponPower: 13,
    strength: 4,
    agility: 0,
    wisdom: 1,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Gold Fishing Rod",
    type: EquipmentType.Fishing_Rod,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 19,
    strength: 6,
    agility: 0,
    wisdom: 0,
    luck: 4,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Plat Fishing Rod",
    type: EquipmentType.Fishing_Rod,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 25,
    strength: 9,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Dementia Rod",
    type: EquipmentType.Fishing_Rod,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 30,
    strength: 12,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Void Imperium Rod",
    type: EquipmentType.Fishing_Rod,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 36,
    strength: 15,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Copper Netted Net",
    type: EquipmentType.Catching_Net,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 9,
    strength: 1,
    agility: 3,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Reinforced Net",
    type: EquipmentType.Catching_Net,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 14,
    strength: 2,
    agility: 4,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Gilded Net",
    type: EquipmentType.Catching_Net,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 20,
    strength: 2,
    agility: 6,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Platinet",
    type: EquipmentType.Catching_Net,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 26,
    strength: 3,
    agility: 7,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Dementia Net",
    type: EquipmentType.Catching_Net,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 31,
    strength: 4,
    agility: 9,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Void Imperium Net",
    type: EquipmentType.Catching_Net,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 37,
    strength: 6,
    agility: 12,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Cardboard Traps",
    type: EquipmentType.Trap_Box,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 4,
    strength: 0,
    agility: 2,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Silkskin Traps",
    type: EquipmentType.Trap_Box,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 8,
    strength: 0,
    agility: 4,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Wooden Traps",
    type: EquipmentType.Trap_Box,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 13,
    strength: 0,
    agility: 7,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Natural Traps",
    type: EquipmentType.Trap_Box,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 20,
    strength: 0,
    agility: 10,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Wax Skull",
    type: EquipmentType.Worship_Skull,
    class: Class.Beginner,
    speed: 4,
    reach: 0,
    weaponPower: 4,
    strength: 0,
    agility: 0,
    wisdom: 2,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Ceramic Skull",
    type: EquipmentType.Worship_Skull,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 8,
    strength: 0,
    agility: 0,
    wisdom: 4,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Horned Skull",
    type: EquipmentType.Worship_Skull,
    class: Class.Beginner,
    speed: 5,
    reach: 0,
    weaponPower: 13,
    strength: 0,
    agility: 0,
    wisdom: 7,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Prickle Skull",
    type: EquipmentType.Worship_Skull,
    class: Class.Beginner,
    speed: 6,
    reach: 0,
    weaponPower: 20,
    strength: 0,
    agility: 0,
    wisdom: 10,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Manifested Skull",
    type: EquipmentType.Worship_Skull,
    class: Class.Beginner,
    speed: 7,
    reach: 0,
    weaponPower: 26,
    strength: 0,
    agility: 0,
    wisdom: 12,
    luck: 0,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "King of Food",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 3,
    strength: 10,
    agility: 10,
    wisdom: 10,
    luck: 10,
    defense: 25,
    miscellaneous: [
      {
        effect: "% Food Effect",
        value: 20,
      },
    ],
  },
  {
    name: "Lucky Lad",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 7,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Total Drop Rate",
        value: 7,
      },
    ],
  },
  {
    name: "Club Member",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 5,
    defense: 5,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 3,
      },
    ],
  },
  {
    name: "Dice Dynamo",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 5,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Luck",
        value: 2,
      },
    ],
  },
  {
    name: "Blunder Hero",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 2,
    strength: 5,
    agility: 5,
    wisdom: 5,
    luck: 5,
    defense: 15,
    miscellaneous: [
      {
        effect: "% Skill AFK Gain Rate",
        value: 3,
      },
    ],
  },
  {
    name: "Trailblazer",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 4,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 3,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 20,
      },
    ],
  },
  {
    name: "Ultra Unboxer",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 3,
    agility: 3,
    wisdom: 3,
    luck: 3,
    defense: 3,
    miscellaneous: [
      {
        effect: "% Total Drop Rate",
        value: 3,
      },
    ],
  },
  {
    name: "Critter Baron",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 0,
    agility: 10,
    wisdom: 0,
    luck: 0,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Agility",
        value: 3,
      },
    ],
  },
  {
    name: "YumYum Sheriff",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 2,
    strength: 8,
    agility: 8,
    wisdom: 8,
    luck: 8,
    defense: 25,
    miscellaneous: [
      {
        effect: "% Boss Damage",
        value: 8,
      },
    ],
  },
  {
    name: "Megalodon",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 5,
    strength: 15,
    agility: 0,
    wisdom: 0,
    luck: 0,
    defense: 30,
    miscellaneous: [
      {
        effect: "% Crit Chance",
        value: 9,
      },
    ],
  },
  {
    name: "Club Maestro",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 1,
    strength: 0,
    agility: 0,
    wisdom: 0,
    luck: 20,
    defense: 20,
    miscellaneous: [
      {
        effect: "% Skill EXP",
        value: 35,
      },
    ],
  },
  {
    name: "Beach Bro",
    type: EquipmentType.Trophy,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 2,
    strength: 5,
    agility: 5,
    wisdom: 5,
    luck: 5,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Money from Monsters",
        value: 50,
      },
    ],
  },
  {
    name: "Smitty's Bubble Blowing Hat",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Bandit Bob Mask",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Paper Bag",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Parasite",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Diamon Horns",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Halloween Pumpkin",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Pardoned Turkey",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Hotdog Hero",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Invisible Hat",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Strawbiggy",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Pop Cat",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Dairy Dunk",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "The Classic",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Green Beanie",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Snowman",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [],
  },
  {
    name: "Giftmas Tree",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 10,
      },
    ],
  },
  {
    name: "Big Bunny",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 11,
      },
    ],
  },
  {
    name: "Fluffy Ramsy",
    type: EquipmentType.Premium_Helmet,
    class: Class.Beginner,
    speed: 0,
    reach: 0,
    weaponPower: 0,
    strength: 1,
    agility: 1,
    wisdom: 1,
    luck: 1,
    defense: 0,
    miscellaneous: [
      {
        effect: "% Monster EXP",
        value: 11,
      },
    ],
  },
];
